version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: nerdery-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/dump.sql:/docker-entrypoint-initdb.d/dump.sql

volumes:
  postgres_data:
