version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: nerdery-container_2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    restart: always

volumes:
  postgres_data:
